apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cafe-services
  namespace: cafe-lumiere
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values: [user-service, order-service, health-service]
  namespaceSelector:
    matchNames: [cafe-lumiere]
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
