apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap.yaml
- secret-template.yaml
- serviceaccount-irsa.yaml
- deployments.yaml
- services.yaml
- postgres-pvc.yaml
- postgres-statefulset.yaml
- ingress-alb.yaml
- hpa.yaml
- networkpolicy.yaml
- pdb.yaml
