apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cafe-alert-rules
  namespace: cafe-lumiere
spec:
  groups:
  - name: availability
    rules:
    - alert: High5xxRate
      expr: sum(rate(http_requests_total{status=~"5.."}[5m])) > 1
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "High 5xx rate detected"
    - alert: PodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total[10m]) > 0
      for: 15m
      labels:
        severity: critical
      annotations:
        summary: "Container restarts detected"
